| create_table                                                                                                                                                                                                                                                                                                                                                                   |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| CREATE TABLE public.comments (is_approved boolean, id integer, content_id integer, user_id integer, text text, parent_id integer, created_at timestamp with time zone, moderation_note text, moderation_score integer, is_flagged boolean);                                                                                                                                    |
| CREATE TABLE public.contents (media_url character varying, media_type character varying, id integer, rating_count integer, growth_index integer, growth_percentage integer, owner_id integer, created_at timestamp with time zone, rating_avg integer, approved boolean, category character varying, creator_description character varying);                                   |
| CREATE TABLE public.creator_profiles (created_at timestamp without time zone, user_id uuid, display_name text, bio text, expertise_area text, is_verified boolean, verification_method text);                                                                                                                                                                                  |
| CREATE TABLE public.creator_verifications (identity_document_path text, admin_note text, created_at timestamp with time zone, reviewed_at timestamp with time zone, id integer, user_id integer, category text, degree_title text, professional_register text, degree_document_path text, register_document_path text, status text);                                           |
| CREATE TABLE public.follows (following_id integer, follower_id integer, id integer, created_at timestamp with time zone);                                                                                                                                                                                                                                                      |
| CREATE TABLE public.likes (video_id uuid, user_id uuid, created_at timestamp without time zone, id integer);                                                                                                                                                                                                                                                                   |
| CREATE TABLE public.login_codes (id integer, email character varying, code character varying, expires_at timestamp with time zone, used boolean, created_at timestamp with time zone);                                                                                                                                                                                         |
| CREATE TABLE public.moderation_queue (video_id uuid, notes text, decision text, moderator_id uuid, reviewed_at timestamp without time zone, id integer);                                                                                                                                                                                                                       |
| CREATE TABLE public.sections (slug text, id integer, name text);                                                                                                                                                                                                                                                                                                               |
| CREATE TABLE public.users (display_name text, id integer, email character varying, username character varying, role character varying, is_active boolean, created_at timestamp with time zone, bio_description text, profile_image_url text, is_creator boolean, is_creator_verified boolean);                                                                                 |
| CREATE TABLE public.video_feedback (video_id integer, score integer, created_at timestamp with time zone, id integer);                                                                                                                                                                                                                                                         |
| CREATE TABLE public.videos (creator_name character varying, title character varying, id integer, rating_avg double precision, created_at timestamp with time zone, growth_percentage double precision, growth_index integer, approved boolean, description character varying, category character varying, video_url character varying, creator_id uuid, rating_count integer); |
| CREATE TABLE public.watch_events (watched_seconds integer, id integer, video_id uuid, user_id uuid, created_at timestamp without time zone, completed boolean);                                                                                                                                                                                                                |